[GLOBAL]
pants_version = "2.14.0"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.lint.black",
]

[source]
root_patterns = ["python", "notebooks"]

[python]
interpreter_constraints = [">=3.8,<3.10"]
enable_resolves = true

[python.resolves]
  dbr_11_3 = "3rdparty/python/dbr_11_3.lock"
  default = "3rdparty/python/default.lock"
  tv = "3rdparty/python/tv.lock"

[pylint]
  version = "pylint==2.15.9"
  lockfile = "3rdparty/python/pylint.lock"

[black]
  version = "black==22.1.0"
  extra_requirements.add = ["click<8.1"]
  lockfile = "3rdparty/python/black.lock"

# [python-repos]
# indexes.add = ["https://pypi.tuna.tsinghua.edu.cn/simple"]

[test]
output = "all"
